### ISSUE TITLE
Components: is the 4 lists needed?

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-XML#119]
I have started implementing BCF 2.1 components and am having som second thoughts about the component lists.

I do think we need 4 DefaultVisibility-attribute for Components, Spaces, SpaceBoundaries and Openings.
However, what do we achieve by having the component list split in 4? I would like the groups feedback on this.

My concern is that we make it unnecessary hard for clients/servers to implement the functionality.

My suggestion is to merge the 4 lists in one list. As far as I can see, all rules would still be handled as previously decided upon:

    component_list: {
        spacesVisible: boolean,
        openingsVisible: boolean,
        spaceBoundariesVisible: boolean,
        componentsVisible: boolean,
        components: [
            ....
        ]
    }

I know this probably is too late to address. Would appreciate your feedback.

**Comment by pbuts** [comment]
I think putting all components in one list would even make it harder to implement because you would not know to which group a component belongs. And you need to know that to give it the right visibility given the default visibility of it's group.

Of course you can find out in the modeler, but that requires an extra lookup to determine it's IFC type and that can turn out quite costly when many components are listed in the viewpoint.

Also, implementations only interested in real components can save the effort of handling spaces etc when it is clear from the group lists.

**Comment by ykulbak** [comment]
@jasollien can you please give a little more detail on how having the four lists makes it harder?

**Comment by jasollien** [comment]
Thank you for your inputs @ykulbak and @pbuts . Here is the main reason for my wish:

Migrate existing database:
With the 4 lists, you will need the IFC-model(s) to migrate to from BCF 2.0 to BCF 2.1.
This is hard to implement since a BCF 2.0-file don't actually have information about which models/revisions it belongs to, and the service might not even have the IFC-model(s)
How should we handle components that we don't know is a space or not?

With one list, it is possible to migrate from BCF 2.0 to BCF 2.1 without the IfC-model(s).
From BCF 2.0 documentation: Spaces, openings and SpaceBoundaries are default hidden which let us now how to set this values.
The Component list visibility can be determined by analyzing the BCF 2.0 components.

By having the IFC-model(s) and analyzing the BCF 2.0, you might find out that the component-list could be optimized by toggling one or more of the visibilities.
When migrating to BCF 2.1 to ONE list, this is the only scenerio where it migth be useful to have the IFC-model(s). However, I don't think we should toggle the visibility when migrating. This analyzation should be done only when creating the Viewpoint initially.

https://github.com/BuildingSMART/BCF-XML/tree/01dba1d78add510dd4d4a2700f7764ca2b417afd/Documentation#optimizing-viewpoint-size

**Comment by jasollien** [comment]
Regarding your input Pieter

I don't actually think the software replaying the viewpoint needs to know if the component is a space or not.
Please correct me if I am wrong on this, but as I have understood:

Initially, when replaying the viewpoint, you use the VisibilityBases to show/hide all components, show/hide spaces, etc...
Then, you show/hide each component in the component-list seperately, since single Component visibility attribute overrides the base attribute. 
So my conclusion would be: YES, initally you need to know the difference between the component types in your IFC-model, but you don't need to know the type for each component in the component-list in the BCF-file.

Please give me feedback on this @pbuts .

**Comment by jasollien** [comment]
"Also, implementations only interested in real components can save the effort of handling spaces etc when it is clear from the group lists."

Yes @pbuts . On this I can agree. The software can get the same behaviour by ignoring the components not found, but for this scenario I agree that it looks cleaner with 4 lists.

**Comment by pasi-paasiala** [comment]
If you only have one list, then when you are receiving BCF, you need to create those lists anyway to apply the default visibilities. I think that is the same when you are writing: You need to sort the components to the lists in the export anyway and you might as well then write the lists as they are instead of creating one big list.

**Comment by jasollien** [comment]
Thank you for input Pasi. Regarding to: "If you only have one list, then when you are receiving BCF, you need to create those lists anyway to apply the default visibilities." If I have understood correctly, you argument for having 4 lists because you will need the 4 lists when showing the components anyway? 

My opinion is that these 4 lists don't help you at all. The reason for that is that you must have EVERY components of a given type to append DefaultVisibility. The BCF only know about a subset of these components. 

After the defaultVisibility is set in the view, you can loop over all components in the BCF-file and override the the visibility to what is set in the Component.

"You need to sort the components to the lists in the export anyway". I am not sure we need to sort them on component type. Could you provide an example?

My intensions here are not to by difficult, or to ensure advantages for bimsync. My intension is to make sure you can migrate your BCF 2.0 file, being sure that the BCF 2.1 file will show you exactly the same. From my point of view, this can only be done in two ways:

1. One list as suggested above
2. Forcing the user to set which IFC-models that are relevant for each viewpoint and making sure the "migrate software" have the IFC-models needed. 

Suggestion one looks for me as the best solution for the end user.

**Comment by ErikPijnenburg** [comment]
To be discussed:
We did some investigation for performance of the new approach. One list is an improvement above 4 lists but still not good:

On viewpoint creation this has to be done:
1. analyse all hidden, visible, selected components in the model to calculate optimum default visibility per group.
2. save hidden or visible and selected components to 1 or 4 lists in BCF viewpoint.

For 1. we need to go through whole model. This is too slow in BIM modelers so we won’t do that. We will always default visibility = false. And save visible/selected objects only = BCF 2.0 method.

On zoom-to this has to be done:
1. apply default visibility to the 4 grouos: objects, spaces, space boundaries, openings: hide all/show all based on default visibility
2. take lists in BCF viewpoint and apply the settings on the objects mentioned

Only if in 1. there is a default visibility = true then we need to go through the whole model, thus making a zoom-to very slow. So we hope (an advise all implementers) for viewpoints with default visibility = false for all groups, then we don’t have to go through whole model and we can offer users a fast zoom-to.

Hidden lists: We advise not to use hidden lists icm with default-visibility = true, since they are very unreliable if not all models were loaded during issue creation, or when models are developped further.
