### ISSUE TITLE
v2.0. Comment status and verbal_status vs topic status and type

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-XML#124]
In BCF version 1, the implementors agreement was that comment_status refers to topic_type, and comment_verbal_status refers to topic status

In BCF version 2.0, bimsync and IABI have treated these values opposite.
- bimsync has kept the agreement from v1.
- IABI has treated comment_status as topic_status and comment_verbal_status as a free text.

I would like the rest of the group to comment with their ways of interpreting comment_status and 
comment_verbal_status in BCF v2.0

**Comment by GeorgDangl** [comment]
We did actually just ignore `comment_verbal_status` =)

But otherwise, yes, we require values used for `topic_status` and `comment_status` both to be defined in the extensions `topic_status` element and `topic_type` is only used for topics `type` property.

Our reasoning is that `topic_type` defines a **category** where an issue belongs to, i.e. _Error_, _Information_ or _Request_ while `topic_status` represents the current **condition** the issue is in, i.e. _Open_, _Resolved_ or _Pending_. This would also match a workflow we expect, e.g. the `topic_type` is assigned at creation time (or may be altered by modifying the topic) where the `topic_status` would change depending on the latest comments `comment_status`.

**Comment by GeorgDangl** [comment]
[Looking at the BCF XML spec](https://github.com/BuildingSMART/BCF-XML/tree/release_2_0/Documentation#status-and-verbalstatus-to-be-phased-out), where exchange scenarios between BCF XML 1.0 and 2.0 are discussed, there's the following passage:
```
When interpreting BCF 1.0 files use the following logic:
 * use Status of most recent comment as value of TopicType
 * use Verbalstatus of most recent comment as TopicStatus.
```
From my understanding, that's because of

1.  BCF XML 1.0 is using the `Status` property for values like _Error_, _Warning_, _Info_ and _Unknown_ while these would more likely be `TopicTypes` in BCF XML 2.0
2. BCF XML 1.0 did allow for any string as `VerbalStatus` property so it's to be used for the current state of an issue

[(Link to the BCF XML 1.0 Spec)](http://www.buildingsmart-tech.org/specifications/bcf-releases/bcfxml-v1/markup.xsd/view)

**Comment by ErikPijnenburg** [comment]
We have had a long discussion about this 3 years ago: #6 
The outcome of that discussion was put in the BCF 2.0 specification:

> **Status and VerbalStatus to be Phased out**
>
> Status and Verbal Status of Comment will be phased out and replaced by TopicStatus and TopicType in Topic.
> 
> When interpreting BCF 1.0 files use the following logic:
> 
> * use Status of most recent comment as value of TopicType
> * use Verbalstatus of most recent comment as TopicStatus.
>
> When interpreting BCF 2.0 or higher files: VerbalStatus and Status on comment level should all be neglected if TopicStatus and TopicType are present in Topic.
> 
> When writing BCF 2.0 or higher files:
> 
> * write the current type and status to Topic's TopicType and TopicStatus
> * write Status and VerbalStatus at Comment level for backward compatibility.
> 

This is how it should be implemented (and we did).

**Comment by jasollien** [comment]
Thank you for a good answer @ErikPijnenburg. A question for all of you. If topic type and topic status is not set in the BCF-2 file. Which comment field do you use for setting the topic type and topic status?

**Comment by ErikPijnenburg** [comment]
Why do you want to do a research how everybody did it?
The answer on your question is implicit in the documentation. If topic type and topic status is not set in the BCF 2.x file then it is in fact a BCF 1.0 approach in that file, and you need to try to use the Status and VerbalStatus of the most recent comment as resp. TopicType and TopicStatus. If they are neither set: use defaults of your/client's choice. If somebody implemented that different than that is against the definition and they should correct it.

**Comment by jasollien** [comment]
The reason for doing this research is that we found IABI doing things different from us. That made me fear that we had implemented things wrongly according to the documentation, and I wondered if anyone else had implemented it equally. Thank you for your answers @ErikPijnenburg.

**Comment by nicktindall** [comment]
If there is no topic type set, we set it to the value of status from the latest comment as determined by ordering the comments by date.

If there is no topic status set, we set it from the verbal_status of the latest comment as determined by ordering the comments by date.

Both are treated as free text.

That's our implementation of the implementors agreement.
