### ISSUE TITLE
Question on Extension.xsd

### ISSUE THREAD

**Issue by daveime** [BuildingSMART/BCF-XML#151]
It seems this extension.xsd allows a predefined set of enum values for various properties inside the main markup.bcf file.

Now who decides what this file contains? The creator of the project? What happens if some drawing software / plugin doesn't support it / re-export it properly, or worse still overwrites it with a different version? Likewise, can any collaborator add to it at will, change the order of the enums etc?

I'm just worried about how to enforce these enum "rules" when parsing a BCF file? Or is it better just to ignore them and allow any / no value to cover any of the eventualities I mentioned above?

**Comment by GeorgDangl** [comment]
In BCF 1.0, the schema itself did specify a fixed list of values to use. This prevented the usage of user defined values, and the values all were in English, too.

For BCF 2.0 (and now 2.1), the approach with the extensible list was taken. However, there's no rule that says who's got authority over the list. When working with a BCF server via the API, it's safe to assume that the server is setting the rules, but this isn't as strict in the file base format.

I'd suggest this approach:
If there are extensions in the BCF file you're reading, treat it as the allowed values. If there's no extensions, all values are allowed.
Even software that doesn't support it explicitly should re-export it again, since all unknown parts of a BCF archive should be re-exported as is.

**Comment by daveime** [comment]
Georg,

Thank you for the prompt response. I had been thinking along similar lines, however it does rely somewhat on 3rd party apps / plugins behaving in the well-behaved manner you describe. If one of our clients is using a plugin that's only supporting v1.0 for example, it might not even understand the presence of the extension.xsd or its purpose.

I guess I was just worried that client A sets the enum as 1,2,3 but client B sets the enum as 1,2,4 for example. Both clients then utilize their enum to set some property from their list of "allowed values", and the server will have to reconcile the two distinct lists and create a new "master list" containing 1,2,3,4 which is redistributed to the clients.

As we're doing a client/server thing in C# anyway, I think I'll have to implement it like that. But not actually using strict ENUM types but List<string> of allowed values.

With server taking precedence / being the oracle for what the enums may contain.

I'll mark the issue as closed now, thanks for your help.
