### ISSUE TITLE
Check ambiguity of FoV (Field of View) in cameras for next version

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-XML#175]
Issue #166 mentioned ambiguity in perspective camera. There is an ambiguity in the direction of the FoV (Field of View), in perspective camera. It works so far in all known implementations, but the direction of the FoV should be explicitly specified in the documentation for the next version.

**Comment by LionelOnTech** [comment]
Created pull request with the documentation change. As per our discussion for the current 2.1 release.

https://github.com/buildingSMART/BCF-XML/pull/176

**Comment by Moult** [comment]
Specification of the horizontal FoV improves the matter, but to be truly complete, an aspect ratio must also be specified. Otherwise, a portrait aspect ratio may display different things to a landscape aspect ratio.

Can I recommend specifying an aspect ratio? This has a few potential benefits:
 - The creation of snapshot.png will be standardised
 - UI implementers have peace of mind about portrait, landscape, or square thumbnailing
 - Any square or aspect cropping may make a decision about whether to zoom first to prevent loss of meaning (i.e. things not visible in the view)
 - Possible benefits to on-screen annotation elements? Haven't checked, just assuming :)

Note: I'm currently implementing BCF in Blender, which has exceptional Camera tools (after all, it is an animation package) and running against this issue.

**Comment by ykulbak** [comment]
We support adding aspect ratio information to viewpoints.
