### ISSUE TITLE
Should camera direction vector be normalized?

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-XML#178]
As discussed in todays telecon, I'm opening this issue to collect feedback about the normalization of vectors used for camera direction.

It's currently not covered by the documentation if a vector should be normalized or not, which leads to some implementations that _do not_ create a normalized vector. Some other applications, however, require the vector to be normalized on import.

Are there any thoughts on vector normalization? As soon as we reach an agreement, we should make sure that the documentation specifies this for the next version.

**Comment by an-ho** [comment]
This is how I see it: If the vector is not normalized, it carries a potentially useful additional information - the distance to the POI (point of interest). This can be used for camera rotation etc.

If a particular implementation does not need that information - no harm done, just normalize the vector yourself after reading it from the BCF!

**Comment by an-ho** [comment]
Sorry, but I can't follow this logic. At all.
Since when does the length of a vector not have an explicit meaning? A vector's length defines a distance between two points. Always.
You have a base point (camera position, in this case), you add an offset vector to it (direction vector, in this case), and you arrive at the POI.
It's basic mathematics; there is nothing confusing or remotely dangerous about it in my mind.

**Comment by dmurrayaconex** [comment]
A vector can have countless meanings, in the case of the difference between two points the magnitude does represent a distance. In the case of a velocity the magnitude represents speed, for a matrix column it may represent scale.
In the case of a direction the only thing we need to know is the ratio between the components. The API should be as unambiguous as possible. Calculating the direction as a difference between two points is only one of many ways of controlling the camera and is an implementation detail.
What do you mean by POI? There are already many mechanisms in BCF for highlighting areas of interest such as selection, colouring and markup. If you are referring to a single point in space then extending a point along the direction vector could only ever give a point in the centre of the screen and what the viewer chose to do with that point would come down to it's specific implementation outside the scope of BCF.

**Comment by an-ho** [comment]
CameraDirection is a GEOMETRIC VECTOR. I don't think we need to argue about that point. A geometric vector describes a direction and a distance. By implying that it could also mean speed or scale in completely different contexts, you are just pulling fictional problems out of your hat.
Applying a geometric vector to a geometric point "carries" you to another point. In this context, that is the "Look at" point, or POI.
Again, there is nothing ambiguous about this.

Now for the POI being outside of BCF's scope: That, at least, is a topic worth discussing.

It is true in the sense that you do not need it to only restore a certain view of your scene.
However, most (if not all) BIM applications will not stop at displaying static scenes, but allow users to continue working with it. Means that the user can rotate the camera. For which the POI is great to have because it gives you something to rotate around. Putting the rotation point one meter in front of the camera, as a normalized direction vector would do, is usually not helpful.
You mentioned BCF's mechanisms for selecting and highlighting; these don't help here either, as should be obvious.
I do not hink this is an exotic use case. I therefore do not think it is outside of BCF's scope to store a camera rotation point (implicitly).
Not storing this info would mean that many applications would have to either store it seperately or "guess" it somehow, resulting in fragmentation.

Especially in this case, I do not see the point of your resistance. I just don't. There is no effort to be made, no change to the current schema necessary. Just allow the already existing CameraDirection vector to be not normalized, and the whole issue goes away.
Storing a length in that vector gives additional information which you don't need to use if you don't need it. So where is the problem?

**Comment by GeorgDangl** [comment]
Hey guys, thanks for your input. I think we should first gather more feedback from other implementations to see if we can get a trend of how this is currently handled in applications.

To summarize, I think we can argue that a normalized vector would make implementations a bit easier, while a non-normalized vector would allow to embed some additional information about the current view.

How is this handled in other applications, for example at bimsync @jasollien, Solibri @pasi-paasiala or Kubus @pbuts?

Let's collect an overview of current implementations first.

**Comment by dmurrayaconex** [comment]
Hi Georg,
Our viewer does have a 'navigation point' which is used as a centre of rotation in the 'orbit' camera mode. We have other camera modes such as walk through and animations that do not use a navigation point.
Specifying the navigation point as a multiple of the cameras forward vector would not be of any use to us as the navigation point is not constrained to the centre of the screen nor does it seem to be in any other viewers I have seen.

It is important that the spec of BCF mean the same thing to all users or it is not doing it's job. Adding undocumented 'features' based on side effects from individual viewers is going against this.

The camera orientation description is already overconstrained. It has 6 degrees of freedom while an orientation only has 3 DOF and most viewers only use 2 DOF. I would also recommend specifying the up vector to be normalised and orthogonal to the forward vector. I understand that the existing schema is more user friendly but as we have seen without these constraints people will start encoding all sorts of random data into the gaps.
Any additional features need to be separate and documented.

**Comment by an-ho** [comment]
It's pretty much the same with us as far as navigation modes go; except that the navigation point of the 'orbit' mode is expected to be at the center of the screen. I don't know how it should work any other way; why would you rotate the camera around a point that you're not looking at?
Hence, we can use the CameraDirection vector to restore the navigation point.

I completely agree to the second paragraph. That's what this discussion is all about; to make clear what the specification actually demands. It _currently_ does NOT demand a normalized forward vector, so implementations should NOT choke on non-normalized vectors.
We actually used a normalized vector in earlier implementations; then I noticed that a non-normalized vector would be
a) useful to us and
b) allowed by the specification,
so I changed it.
If I read you correctly, you are for storing a navigation point, but against doing it in the CameraDirection vector? For me, that would be redundant, but OK.

All agreed on the third paragraph. While it (currently) does not cause any issues as far as I'm concerned, it is true that the up vector could (and probably should) be more constrained.
