### ISSUE TITLE
Fails to parse xsd in version 2.1

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-XML#183]
Get this error when generating java-classes using jaxb2-maven-plugin (v 2.5.0)

![image](https://user-images.githubusercontent.com/3275463/70057887-34bdd300-15de-11ea-9891-756ee6549d5f.png)

The proplem goes away if I remove these lines in visinfo.xsd.

![image](https://user-images.githubusercontent.com/3275463/70057933-4b642a00-15de-11ea-8b71-f44d1b63ece0.png)

**Comment by GeorgDangl** [comment]
@cbenghi, please take a look at the XSD validity.

**Comment by CBenghi** [comment]
Sure, 
I add this comment so that you can assign me.
C

**Comment by CBenghi** [comment]
Hi @jasollien,

I've looked at the valid types at https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#built-in-datatypes

```
    3.3 Primitive Datatypes
string · boolean · decimal · float · double · duration · dateTime · time · date · gYearMonth · gYear · gMonthDay · gDay · gMonth · hexBinary · base64Binary · anyURI · QName · NOTATION
    3.4 Other Built-in Datatypes
normalizedString · token · language · NMTOKEN · NMTOKENS · Name · NCName · ID · IDREF · IDREFS · ENTITY · ENTITIES · integer · nonPositiveInteger · negativeInteger · long · int · short · byte · nonNegativeInteger · unsignedLong · unsignedInt · unsignedShort · unsignedByte · positiveInteger · yearMonthDuration · dayTimeDuration · dateTimeStamp
```

`Guid` does not seem to be in the list, so it makes sense for it to be defined in the file.
We have tried to have it validated during the call from an online Java XSD validator and it passed; I've later tried with Visual studio  XSD tool and it also worked as it is.

I wonder if this your issue derived from the combined parsing of 
https://github.com/buildingSMART/BCF-XML/blob/d67e2a16425f4740182084bba4c937b1b36198c1/Schemas/visinfo.xsd#L186
and
https://github.com/buildingSMART/BCF-XML/blob/d67e2a16425f4740182084bba4c937b1b36198c1/Schemas/markup.xsd#L138
due to `Guid` type being defined in two files.

If this was the case, though, we would encounter similar problems for IfcGuid and other types.
Can you still reproduce this in a new project?

Thanks,
Claudio
