### ISSUE TITLE
Is there an official Content-Type for BCF files?

### ISSUE THREAD

**Issue by Amoki** [buildingSMART/BCF-XML#192]
When generating browser downloads, it could be great to have a mime/content-type to let browsers determine the type of the file and suggest applications to open them.

I tried to search for it but couldn't find anything.

**Comment by GeorgDangl** [comment]
Hey @Amoki, thanks for raising this issue!
We're not against having our own mime type, but how would we do that? Do we have to register it somewhere?

**Comment by Amoki** [comment]
There is two way to define a mime type: using a private value, or registering a standard one to the IANA. We may not need to register one. The registration procedure is defined here: https://tools.ietf.org/html/rfc2048

The syntax is defined here: https://tools.ietf.org/html/rfc2045#section-5.1 and some details are added here: https://tools.ietf.org/html/rfc2046#section-4.5

In our case, it could be at least `application/x-bcf` but it could be great to add the version number.
I suggest `application/x-bcf ;version=2.1` over `application/x-bcf-2-1`. Apps won't have to define many content-types for all BCF versions and users won't be lost if they download an incompatible BCF and their preferred software doesn't show up.

**Comment by CBenghi** [comment]
This has been postponed in the call today because it's not clear what would be the benefits and risks of setting a different content type.

Risks discussed:
- Would there be scenarios where the client would not download the file if it does not know the content type?
- How would the association happen at client level? Can that be retained or have to be re-associated frequently?
- How would we be expected to deal with a server that still specifies the old content type (for any transitional time or possibly forever)?

Admittedly there was limited expertise on the topic in the call, but benefits were also not clear. 

@Amoki, would you be able to explicit the benefits? Thanks!

**Comment by Amoki** [comment]
When downloading a file from the web, the browser asks:
* If we want to download the file (by default in the Downloads directory)
* If we want to open it with a compatible software if available (eg: LibreOffice or Word for .docx files). In this case, the file is downloaded in a temporary directory and opened automatically. The user doesn't really know where the file is. The software must signal the content type they're compatible with https://stackoverflow.com/questions/6267546/how-do-i-associate-a-custom-mime-type-to-my-local-application-in-the-major-brows
* If we want to open the file directly in the browser, bypassing the "download" process (eg: pdf, videos). (This won't be the case for BCF files)

The browser doesn't use the extension to guess compatible software, it uses the Content-Type.
It's the responsibility of the web-server to define the Content-Type of the served content.

If there is a Content-Type defined, the browser will ask to download and save the file or open it directly with any installed BCF program. 
If there is no Content-Type, the browser will just ask to download the file.

I see no backward incompatibility.

There are more and more web BIM platforms, users share BCF files on these platforms and the workflow could be improved between web services and installed software with this feature.
