### ISSUE TITLE
Viewpoints should have date and author properties

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-XML#207]
As discussed in the call, viewpoints should both have a date and author information attached to them, e.g. a `CreationDate` and `CreationAuthor`.

**Comment by cschladetsch** [comment]
Should or Must? Surely this information is available when the Viewpoint is created, however, it may not be relevant in many later use-cases. Even so, it could be useful with little effort to make it a Must and hence have more context-tracing for viewpoints.

**Comment by emaschas** [comment]
Viewpoints are referenced by Comments otherwise they belong to the Topic.
Both Comments and Topics have a Creation / Modification date and author.
We don't track the history of modifications for the Comments nor for the Topic, why should we do so for the viewpoints ?
Shall we consider Viewpoints independantly from Topics and Comments ?

**Comment by GeorgDangl** [comment]
Tracked here: https://github.com/buildingSMART/BCF-API/issues/181
