### ISSUE TITLE
Add ServerAssignedId to BCF-XML 

### ISSUE THREAD

**Issue by ykulbak** [buildingSMART/BCF-XML#232]
This would align BCF-XML with [BCF-API](https://github.com/buildingSMART/BCF-API/issues/201)

**Comment by jasollien** [comment]
I do not think we should include server_id to the BCF xml. 

Why: 

1. In the BCF-API, there are clear roles between the server and the client, where the server is the source of truth.
In BCF-xml, there are no such roles. The source of truth is the BCF-file itself, not the application creating it, and not the application reading it.

In the case of a roundtrip, typically a user will import the BCF-file, and maybe synchronize that to a BCF-server using the BCF-API. A new server_id would then be created on the server, and you will have two server_ids for that same topic.
Which server_id should the client display to the user now? 

I fear, that by introducing this, we will go into the same issue that we had with guids, all over again.

@ykulbak, @pasi-paasiala and others. Can you give your inputs on this?

**Comment by CBenghi** [comment]
Thinking again about this, I kind of agree with @jasollien.

However, I also see the benefit of having an external reference ID for the items.
An interesting solution would be to have a collection of external references instead than just one server-id.
This might be interesting in use-cases that help reconcile work done across multiple CDEs.

If this was the case I'm not sure if URIs or couples of Server/Server-Ids would serve the purpose better.

This is because the proposed implementation with just server-Id would fail to reconcile clearly with an online resource on its own, or is the server location stored in some other XML field?

**Comment by pasi-paasiala** [comment]
We were discussing this as well yesterday in our hackathon breakout group. This makes sense in the case when BCF is created from server. A client should never give a value to server_id. BCF-API should be the goto solution and only for software not supporting it, BCF-XML should be created from server. We could also have multiple identities, but I feel that it is a bit of an overkill.

**Comment by ykulbak** [comment]
In the open cde Hackathon we resolved to add an optional `server_assigned_id` that should never be added by clients and ignored when imported on the server.

**Comment by CBenghi** [comment]
For naming consistency the XML naming should probably be `ServerAssignedId`. I'm preparing a PR with the changes.

**Comment by ykulbak** [comment]
Closed by #236
