### ISSUE TITLE
Aspect ratio. How should correct view with aspect ratio be displayed?

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-XML#243]
After adding aspect ratio, we know the ratio of the screen, but how can we actually display the correct view.

Let's say we create a viewpoint with aspect < 1, example 0.5.

Then, you want to display this on a wide screen, example aspect = 2.0

From the documentation:
"When reproducing a camera viewpoint on a system that cannot adjust aspect ratio, the actual camera parameters shall be determined to ensure that all the contents of the original view box or view frustum are displayed, this might result in extra model content visible beyond the original view."

- The first that comes to my mind, is to "zoom out", so that you can view the missing parts. However, by doing this, the camera might end up behind a wall, which makes the viewpoint useless.

- Another option is to change the "field of view", but this is a bad option, as the field of view will actually be different from what it is set to be by the user.

- Third option is to make the viewer box itself a lot smaller, so that it can match the original aspect, but this is also a bad solution as if will cause additional navigation in the viewer to behave poorly.

- Last option is to modify near plane, but since this is not sent in, we do actually not know actually know the input in the calculation.

Could anyone explain what best practice should be, or if this is actually not possible to achieve in all scenarios?

**Comment by CBenghi** [comment]
Hi @jasollien,

You are correct that this is unclear, but in the call it was decided to accept the current state of uncertainty for the release (2.2, now 3.0) since a complete specification and implementation did not appear feasible in the timeframe desired to finalise the version.

As such this should be marked for 3.1 or 4.0 milestones, and clear guidelines added for implementations that do not allow the change in ratio, possibly with the addition of more fields.

On the matter:

1.  zoom out could be done, together with changes in the front clipping (which is not defined in the format, but applications know what they are using). cons: this does not respect the camera position stated by the user, and has issues with other forms of occlusion.
2. change in FoV seems the easiest option to implement, and the one with least impact on occlusion changes.
3. It was discussed in the call that opaque or semi-opaque bands could be added to the view, and they could be activated/deactivated either with UI or timer.
4. the change in the near plane could be coupled with the change in position, but in my view this is the less conformant solution.

Beyond the standard, this is a difficult UI decision, it will need a detailed conversation.

**Comment by CBenghi** [comment]
It was agreed in the meeting to keep the data standard as it is and improve the documentation with more precise instructions.

There was informal consensus over option 2 as the default course of action, pending doubts over the visual distortion in extreme cases. I'll try to address these in a documentation update.

**Comment by CBenghi** [comment]
I have a working implementation of the camera adjustment code proposed in the PR above that can be demonstrate during the call, if useful.

**Comment by ykulbak** [comment]
Closed by #276; Thanks @CBenghi !
