### ISSUE TITLE
Example files should use correct detailed_version

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#265]
right now version id and detailed version are identical. I think this is not the intention from looking at the BCF-API.

**Comment by GeorgDangl** [comment]
From discussion in the group today, we should create a template file for the `bcf.version` file that's unique for each release and which contains the values to use.
The template files are already available:
* v2.1: https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Documentation/bcf.version
* v3.0: https://github.com/buildingSMART/BCF-XML/blob/release_3_0/Documentation/bcf.version

Since there's no use case for the `DetailedVersion` element, we'll remove it from the XML and API spec.
