### ISSUE TITLE
URI syntax ambiguous

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#336]
A URI is needed a few times in the spec. Very minor clarification that what is actually meant is "URI Reference" and not "URI"?

Further reading:

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#URI_references

**Comment by GeorgDangl** [comment]
Hey @Moult, thank you for raising this! I was not aware that there's a difference between _Uri_ and _Uri Reference_. So if I understood it right, an _Uri_ per the Wikipedia definitions always must include a scheme, e.g. `http:` or `file:`, where an _Uri Reference_ is really just a unique resource identifier, a string that uniquely identifiers a resource.

Do you know if there's an official standard for that? I have always been under the impression that anything that uniquely identifies a resource is an _Uri_, and the special case where the _Uri_ also points to where the resource can be found is an _Url_, an _Uniform Resource Locator_. So that's why we went with just calling it _Uri_.

Wikipedia seems to also define both _Url_ and _Urn_ (as _Uniform resource name). If I understand it correct, all _Url_s and _Urn_s are _Uri_s, but the reverse isn't true.

Here's a link to the RFC describing the three types: https://tools.ietf.org/html/rfc3986#section-1.1.3

So, that all sounds pretty confusing😀 The question is, do we need to clarify something? I have the feeling that most people who read the standard would understand what an Uri is, but differentiating between Urn and Url would make it a bit more complex.

@pasi-paasiala, @jasollien, @ykulbak, what do you guys think?
