### ISSUE TITLE
Topic history

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-XML#97]
Currently there are no good ways to represent the history of what has been done in BCF.

In the older version, comments were used for the history, but it was limited.

The suggestion is to add an array: "history" in the bcf-xml schema. 

Every history items contains:
topicGuid: guid of the topic
type: An enumerated value of the change type. See example under
value: the value of the change, etc name of status, title, label etc..
date: the date for the change
modifier: the user that made the change

Example of history types:
    status-changed, 
    type-changed, 
    priority-changed,
    assigned-changed,
    title-changed,
    description-changed,
    label-added,
    label-removed

It is up to the server to decide whetever they would like to maintain this array, but they should at least keep the values for roundtripping.

If wanted, this history table can also represent everything that is done in bcf. Perhaps by renaming "topicGuid" to "resourceGuid" and adding a new field "resourceType".

This array can also be used for synchronizing the client with the BCF-api. Example resource method: give me everyhing that changed after august 22, 10 am.

Please feel free to comment.

**Comment by venilillkall** [comment]
Can you describe the use case you have for full BCF XML history?

With multiple clients taking part in the BCF file exchange it is hard to maintain a reliable history unless it is made mandatory for all clients - even then it is up to all clients to play nicely.
For BCF API on the server side this could work (but likely would not be mandatory either), if the server wants to implement full topic history,

Notice that object insertion change-type requires the full object to be stored as the value - or separate history items for each object property. If implemented fully this will increase the size of BCFs.

**Comment by ErikPijnenburg** [comment]
The only way to have a reliable history is when working with a BCF hub (wether or not via the BCF API). It makes no sene to try to get this done with BCF files.

**Comment by gschleusner** [comment]
I agree with not putting the full history in the schema, it would make sense for a record in the BCF that can link to a change record.   This would allow a block chain like implementation that can have a pointer to a hosted change history.  Without this you'd loose the ability to move between hosted and non-hosted systems.  I think having the ability to do both is important.

**Comment by GeorgDangl** [comment]
Will be moved to BCF API

**Comment by lbj** [comment]
While i fully agree in the shortcomings in trusting 100% in a mixed scenario using files and API I think ignoring the problem and a need for a solution is wrong. Especially knowing that the API also has postponed the history bit to version 3.0. (at least for now).  Version 1 supported history rather clumsily by allowing to store type and status along the comment (with it's date and time). While not being ideal this did after all fulfill the need for being able to store the history of issues in a given project. In a BCF 2 file exchange you see the latest status but you have no idea what happened along the way. Do you guys really think no one is interested in knowing the history of this type of information?  
(See related API comment : https://github.com/BuildingSMART/BCF-API/issues/19 ) I'm reopening this as its currently unresolved both in the file version as well as in the API.

**Comment by rasso** [comment]
We are now in the commenting phase for the next BCF-release. If there is a strong opinion for support of history (which personally I support), then this has to be taken into account by the BCF-group, and only very strong arguments could postpone this to to BCF 3.0. That's how standard's balloting works.

To add my penny to the XML versus API discussion: sending around BCF-XML-files is as old-fashioned and humble like sending information via fax or paper-mail. The only reason why I still have to send fax are requests by banks. The joke is, that in the meantime I'm using an app mimicking a fax machine to send them a scan of the documents, but they do not accept the same scan via e-mail. If they would offer an API, a secured communication could be established, much safer than these virtual fax-mashines.

We should agree on, that BCF-API is the preferred way and should optimize everything for this communication channel. BCF-XML should only be considered as a humble fall-back solution.
--
Rasso

Sent from mobile device

Am 13.09.2016 um 00:01 schrieb Lars <notifications@github.com<mailto:notifications@github.com>>:


While i fully agree in the shortcomings in trusting 100% in a mixed scenario using files and API I think ignoring the problem and a need for a solution is wrong. Especially knowing that the API also has postponed the history bit to version 3.0. (at least for now). Version 1 supported history rather clumsily by allowing to store type and status along the comment (with it's date and time). While not being ideal this did after all fulfill the need for being able to store the history of issues in a given project. In a BCF 2 file exchange you see the latest status but you have no idea what happened along the way. Do you guys really think no one is interested in knowing the history of this type of information?

(See related API comment : BuildingSMART/BCF-API#19<https://github.com/BuildingSMART/BCF-API/issues/19> ) I'm reopening this as its currently unresolved both in the file version as well as in the API.

-

**Comment by jasollien** [comment]
> Can  you describe the use case you have for full BCF XML history?

Use case for full BCF XML history?
While I think everything stored in BCF should be historized, I think Topic history is most important. We have experience with having full history in Topics in bimsync, and the example above works great as the structur on our Topic database.

Mandatory? 
I agree it may not have to be mandatory, but it does for sure increase the value for the clients implementing it. What’s important, is to have the possibility to export the data through the BCF-format. 

Size of BCF?
Yes, this will slightly increase the size of BCF. But not much. If the description equals 1 full page of text (highly unlikely), which equals 2KB (ref1), yes, you will get 1 extra MB when changing the description 500 times (also unlikely). 
Of course, we could have some limit on the history length and in the ”value” field.
Example: Max 100 ”histories” for each event, and max 10000 character length for the ”value” field.

Conclusion: Yes it may increase the size, but not considerably.

Ref1: http://pc.net/helpcenter/answers/how_much_text_in_one_megabyte

**Comment by CapnK** [comment]
Arup have 30+ project using the evolution of the Issue Tracker that CASE created (BCF+Jira)
https://github.com/ArupAus/issue-tracker/tree/arup_2016_support_bcf2 

Some of those projects have >600 issues which have gone through 5-6 status changes involving 2-3 assignees and 3-4 comments each.
Granted Jira is effectively doing the 'topic history' for us, but I've not (yet) had a user request to report upon the topic history.  (Most requests have been about the current state of the project/topics) 

So my concern would be the performance/bloating of adding the extra history to a BCF-XML.
If it were limited to the topic history, and is an optional set of data, then it might reduce the impact.

One question would be:  If we go down this route, what might need to be unpicked once BCF-API properly supports it?  
I suspect the BCF-API is going to need support for 'retrospectively add/merge history in the name of a different user' (i.e. add the history of changes since a date)

**Comment by ErikPijnenburg** [comment]
What are we trying to solve here?
In my view history can only be reliable on a hub when files are merged frequently (needed anyway for up-to-date information). Otherwise you will always get at some point a history distributed over several files, thus unreliable.
So the only use case I can imagine is archiving a complete project from a BCF hub (usable as well for full project-data-exchange between hubs). If people want to go that way I suggest NOT to pack normal BCF files with this info (to keep this light and simple, which is part of BCF's success) but define a extended BCF-Archive format. Not mandatory.

**Comment by lbj** [comment]
In my opinion we are trying to resolve two use-cases here:

1. For file exchange: To assure that the complete history of how issues are handled in projects can be exchanged between two BCF hubs/servers. I assume we do not intent to lock in a project to one BCF server just because there is no way of getting the history out on a standardized format. I would argue that being able to exchange and store what has happened to a topic in BCF is absolutely within the scope of the standard. And while some of you might not yet have got the request to preserve and exchange history of issues this is a demand from many of our customers. 

2. For API use. To assure that a BCF client is able to present a discussion around a topic the way the discussion took place. This is a major shortcoming of the current BCF API specification. 
When you retrieve a topic using the BCF API you see the current status and type of the issue but you have no idea what the initial status was, what the status was when a given comment was made, if the topic has changed its' topic-type or status or by whom. Removing the knowledge about what has happened during a discussion is in my opinion doomed to cause conflicts and misunderstandings in projects. I also think fixing this is well within the scope of BCF and should not be outsourced to systems like Jira or similar. 

And finally. If the fear of bloating the BCF format is an issue we should rather focus on getting some kind of basic understanding of the ifc model into the viewpoints. Viewponts are by far the larges blobs of information in a BCF exchange. Often megabytes in size while the markup (where history would reside) are a few hundred bytes. Instead of listing thousands of GUIDs in order to show or hide everything on a floor, in a system or of a type there are plenty ways to use our knowledge about ifc to make viewpoints much smaller.

**Comment by gschleusner** [comment]
I would add to yes camp on having the history on a file level as some tools don't have APIs that allow you to add your own connection to them and thus a file based exchange is required.  Unless the standard actually states and requires a user editable Rest APIconnect then its certain something we would need.

**Comment by Stevishere** [comment]
I could not agree more with Rosso’s comments about the API vs XML.  This is the 21st century.  API offers far more robust possibilities as the BCF matures.  Also, we must have all stakeholders think in terms of a data store for every facility.  A datastore is housed wholly, not a file that is distributed or shared.  Any such distribution offers fragmentation and versioning problems the moment it is issued.

Regards,

Steve Holzer

Phone/Text: 804.389.4947

Have you registered to change the world in the next AEC Hackathon?<http://www.aechackathon.com/>

**Comment by pasi-paasiala** [comment]
I also think that history shouldn't be part of the file based exchange. If it is available somewhere, it should be in BCF-API.

**Comment by gernotewert** [comment]
I would just like to bring up the use case of archiving the topics at the end of a project or for a data drop. In this case a server would export those topics as BCF and should be able to also include the history. Additionally it is possible to have BCF's in a phase of the project where no CDE is fully setup.
